# Generated by Django 5.0.4 on 2024-05-15 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroModel',
            new_name='Registro',
        ),
    ]
