# Generated by Django 5.0.4 on 2024-05-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_registromodel_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='lugar',
            field=models.CharField(default='', max_length=100),
        ),
    ]
